DEFINE VARIABLE cnt AS INTEGER NO-UNDO INIT 1.
DEFINE VARIABLE EndlessCount AS INTEGER NO-UNDO INIT 1.
DEFINE VARIABLE l  AS LOGICAL NO-UNDO.
DEFINE VARIABLE l2 AS LOGICAL NO-UNDO.
DEFINE VARIABLE l3 AS LOGICAL NO-UNDO.
 
DO WHILE cnt < 3:
IF l THEN
DO:
    RUN test1.p.
    RUN test2.p.
END.
ELSE IF l2 THEN
DO:
    RUN test3.p.
    RUN test4.p.
END.
ELSE IF l3 THEN
    RUN test5.p.
ELSE
    RUN test6.p.
END.

REPEAT STOP-AFTER 1:
     IF EndlessCount > 2000 THEN LEAVE.
     ELSE ASSIGN EndlessCount = EndlessCount + 1.
END.